### PR TITLE
Update CMakeLists.txt: Be a bit more flexible towards linking Eigen

### PR DESCRIPTION
**Pull request by GenieTim**
This change allows me to use `FetchContent_Declare` for both `Eigen3` as well as `Spectra`.

### CODE REVIEW

**Review by yixuan — COMMENTED** [review]
Thanks for the PR. I am not familiar with CMake variables. Is `EIGEN3_LIBRARIES` always defined?

**Comment by GenieTim** [comment]
> Is EIGEN3_LIBRARIES always defined?

Unfortunately, I am neither particularly familiar.

I tried to investigate where the variable is coming from in my projects, but no luck – I have no clue, neither the CMake `find_package` documentation nor Eigen's cmake files seem to contain any reference that would help me.

I have adjusted my PR to first check whether the variable is defined, and if not, fallback to the "original" way of linking.

**Comment by yixuan** [comment]
Just curious: if your project does not contain this variable, then why it needs to be in the CMake file? I thought `Eigen3::Eigen` is a pretty fixed and stable target for the Eigen library.

**Comment by GenieTim** [comment]
Excellent question. I just checked what the value of EIGEN3_LIBRARIES is, and with which system it is actually needed (i.e., where `TARGET Eigen3::Eigen` evaluates to false). I did not find as many systems as I thought I had, actually only one in a large GitHub Action matrix where it is set, which should help me figure out where it comes from. 

It seems the other cases where I could not compile Spectra properly were not caused by this issue here, but by me not declaring the Eigen3 as a dependency of Spectra, leading to Eigen3 being fetched (with `FetchContent_Declare`) too late, and the Eigen3::Eigen target not being available yet when Spectra is fetched. By using the fix presented here (before the variable existence check), the variable was empty, and the link worked (as no link was made), and then in the end my library was linked to Eigen, leading to Eigen being generally linked correctly.

Thank you for pointing out the imperative correctness of `Eigen3::Eigen`, I will close this PR and debug the remaining case separately.

**Pull request closed without merging**
