### PR TITLE
Removed std:: specifications for Scalar objects. This allows the comp…

### PR DESCRIPTION
**Pull request by jdbancal**
...iler to choose the implementations of abs, sqrt, pow which is suited to the used type.

Thanks for the tip on adjusting the source code for other types than builtins like float and double! I did these changes and it works for me :-) It would be great if anyone using your code could benefit from this.

I couldn't check all the methods since I'm not sure how to use all of them... But I used DenseSymMatProd and SymEigsSolver and applied the same changes to all files.

Note that "#include <cmath>" is now commented out, since it is only needed if Scalar = float or double. It should thus be included in the files relying on Spectra if they choose to have fload or double matrices (before the Spectra includes).

### CODE REVIEW

**Comment by yixuan** [comment]
Hi @jdbancal, thanks for this careful PR. However I see that there is some complication here.

For example for the `abs` function, when used as a free function, its definition is a bit ambiguous. From the C library, `abs` applies to integers, and `fabs` applies to float numbers. In contrast, `std::abs` is more portable and standardized.

I think you can solve your problem without changing these `std::` specifications. You can simply define the math functions of your float type in the `std` namespace. For example in your code, you can define

```cpp
namespace std {

MyRealType abs(MyRealType x)
{
    // blablabla
}

MyRealType sqrt(MyRealType x)
{
    // blablabla
}

}  // namespace std
```

It should have the same effect.

**Comment by jdbancal** [comment]
Hi @yixuan,

Thanks for your quick reply!

I agree that completing the std namespace could a priori be a possibility, although I suspect a bad one: about completing namespace std:: see for instance http://stackoverflow.com/questions/22701354/is-it-a-good-practice-to-overload-math-functions-in-namespace-std-in-c . Do you think that making non-standard code is a good idea?

Also, this is not the Eigen way: Eigen works with matrices of arbitrary type, and it includes some functions like abs or sqrt (forgot which one exactly, but can be found easily). In none of these cases does Eigen relies on the std namespace. Rather, it calls simply the function itslef (e.g. 'abs' without std::) and lets the compiler find the relevant implementation. It is then the programmer's responsability to include the definition of the required math functions.

In your case, could it be that your test fails because it only find the super basic abs function, which is only implemented for integers (i.e. it doesn't find one which applies to type double) ? As mentioned, I commented out the "#include <cmath>" statements, therefore, one way to correct this would be to add this statement at the beginning of your file (because you need to provide the basic math function for the type that you are dealing with). In case you prefer the Spectra library to support double formats by default, you can also just uncomment the cmath include statements.

**Comment by yixuan** [comment]
OK. Maybe the preferred way is to follow what Eigen does in [this example](https://bitbucket.org/eigen/eigen/src/26667be4f70baf4f0d39e96f330714c87b399090/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h?at=default&fileviewer=file-view-default#SelfAdjointEigenSolver.h-721): add a `using` statement before calling the `abs` or `sqrt` functions.

(I found that Eigen also has some direct calls to `std` functions, which can be avoided as you said, for example [here](https://bitbucket.org/eigen/eigen/src/26667be4f70baf4f0d39e96f330714c87b399090/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h?at=default&fileviewer=file-view-default#SelfAdjointEigenSolver.h-618))

**Comment by jdbancal** [comment]
Right, indeed it seems that Eigen still has a few std around. Not sure why...

I agree it would be nice to follow Eigen :+1:

**Comment by yixuan** [comment]
Already merged. Thanks!

**Comment by jdbancal** [comment]
Awesome! Much appreciated :-)

**Pull request merged**
